### ISSUE TITLE
Break Out or Move NON-SCAD Functionality

### ISSUE THREAD

**Issue by z3dev** [jscad/scad-api#24]
I did an analysis of SCAD versus JSCAD functionality, which shows that there is a lot of "extra" functionality in the library. If some of this is useful to other libraries then these functions should be broken out/moved.

Review of OpenScad vs OpenJsCad OpenScad
J: defined by Javascript
I: translator required
*: defined in OpenScad and in OpenJsCad OpenScad
-: defined in OpenScad but not in OpenJsCad OpenScad
+: not defined in OpenScad but in OpenJsCad OpenScad

Syntax:
J: var = value;
I: module name(…) {…}
J: function name(…) = …
*: include <…> acts as if the contents were written inline
-: use <…> imports declarations of modules and functions

2D
*: circle(radius | d=diameter)
*: square(size,center)
*: square([width,height],center)
*: polygon([points])
*: polygon([points],[paths])
-: text(t,size,font,halign,valuing,spacing,direction,language,script)

3D
*: sphere(radius | d=diameter)
*: cube(size,center)
*: cube([width,depth,height],center)
*: cylinder(h,r | d,center)
*: cylinder(h,r1 | d1,r2 | d2,center)
*: polyhedron(points,triangles,convexity)

Transformations
*: translate([x,y,z])
*: rotate([x,y,z])
*: scale([x,y,z])
-: resize([x,y,z],auto)
*: mirror([x,y,z])
-: multmatrix(m)
*: color(“name”)
*: color([r,g,b,a])
-: offset(r | delta,chamfer)
*: hull()
-: minkowski()

Boolean
*: union()
*: difference()
*: intersection()

Modifiers
I: “*” disable
I: “!” show only
I: “#” highlight
I: “%” transparent

Math
…

Functions
	contact
*: lookup
	str
	chr
	search
*: version
-: version_num
	norm
	cross
	parent_module(idx)

Other
*: echo(…)
J: for …
I: intersection_for …
J: if (…) {…}
I: assign (…) {…}
-: import(“filepath”) imports the model (2D DXF or 3D STL) for use // NOTE: import is a reserved word in javascript
*: linear_extrude(height,centre,convexity,twist,slices)
*: rotate_extrude(convexity)
	surface()
-: projection(cut)
	render(convexity)
	children([idx])

Only in OpenJSCad OpenScad.js
+: group(objects)
+: geodesicShere()
+: torus()
+: center()
+: expand()
+: contract()
+: chain_hull()
+: rectangular_extrude()
+: triangle()
+: rgb2hsl()
+: hsl2rgb()
+: rgb2hsv()
+: hsl2rgb()
+: html2rgb() // required for HTML color
+: rgb2html() // required for HTML color
+: simplexFont()
+: vector_char()
+: vector_text()
+: clone() … internal only (not used)
+: sprintf() … internal only (not used)
+: vsprintf() … internal only (not used)

**Comment by kaosat-dev** [comment]
This is a very good & useful analysis @z3dev !
It will help fill in the blanks, but I do not think APIs should become even more fragmented than before: despite the naming  of this package , I do not think we need to copy 100% what Openscad does,  moving towards a functional , clear & clean API is , which this package is a good step towards ?

**Comment by faithhack** [comment]
Great list! After porting some modules from SCAD to JSCAD, I can add that OpenSCAD's search() is not in OpenJSCAD and OpenJSCAD's hull() is missing functionality as it can't do 3d hulls like SCAD's can. 

I would like to see as complete a mirror of SCAD's api as possible - or some snippets in the docs on how to emulate SCAD where it may not be worth the effort to implement code in scad-api. There is tons of SCAD modules out there waiting to be porting over :-)
