### ISSUE TITLE
color transparency fails except for red?

### ISSUE THREAD

**Issue by z3dev** [jscad/scad-api#3]
_From @biscuitlad on February 24, 2016 15:4_

 box = color("palegreen", 0.8, box);  //fails
 lid = color("red", 0.8, lid);   //works

Red will be transparent, any other colour seems to fail.  You can swap these and still one will fail and the other work.  

_Copied from original issue: Spiritdude/OpenJSCAD.org#132_

**Comment by z3dev** [comment]
@biscuitlad you found a bug. I'm not sure what the issue is at this time, but was able to reproduce the issue.

It seems that other color names do not work, like "blue", "palegreen", etc. And as you mentioned, "red" works.

**Comment by kaosat-dev** [comment]
so does this mean the color lookup is failing ?

**Comment by z3dev** [comment]
I'm writing the test now. I'll let you know.

By the way, this requires a table of CSS color names and RGB values. Not sure if this table needs to be exposed, but I'm going to export css2rgb() and rgb2css() functions.

**Comment by kaosat-dev** [comment]
does this mean that this code is not for css color names ?
https://github.com/jscad/scad-api/blob/master/src/color.js#L4

**Comment by z3dev** [comment]
The color list is CSS. But there's no way to convert directly from CSS name to RGB. The current function applies the color to an object. I want to separate our the css2rgb(), and change color() to call css2rgb() to get the color from the list, and then apply the color to the object. Slightly different.

**Comment by kaosat-dev** [comment]
ah yes, very nice, good idea, thanks for the clarification

**Comment by z3dev** [comment]
I believe this is now fixed with the merge of #5 
A final review would be appreciated.

**Comment by kaosat-dev** [comment]
Looks good to me ! Closing
