### ISSUE TITLE
Proposal: Simplify parameter handling for transform operations :  use rest parameters

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/scad-api#32]
The polymorphism of some our functions leads to useless complexity, and too many ways to do the same thing:
for example `translate()` can currently be done: in all these ways
```javascript
1- translate([10, 2, 0], shape)
2- translate([10, 2, 0], shapeA, shapeB)
3- translate([10, 2, 0], [shapeA, shapeB])
```
Which  additional checks internally to determine what shapes are passed in
I propose the following:
- drop support for array support in that shape BUT
- support it via [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters)
This means the useage with arrays  (from example above) becomes : 
```javascript
translate([10, 2, 0], ...[shapeA, shapeB])
```

This means:
- simplified parameter handling internally , since rest parameters means we always get an array, which means potential speedups (less additional checks)
- no more need to access the 'arguments' object [which](http://airbnb.io/javascript/#es6-rest) is discouraged
- a more coherent API: rest parameters just 'unpacks' the array to be the same as (2)
- rest parameters are [widely supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters#Browser_compatibility)

**Comment by z3dev** [comment]
@kaosat-dev the proposal is good because the API aligns with web standards as well as interoperability standards. I favor anything that moves that way.

However, I once again make a case that this is the "SCAD" compatibility API library. The proposal is will not maintain this compatibility layer.

I'm wondering if another API layer should be created which combines all the functionality found in CSG API and SCAD API. The CSG API needs to be broken away from the CORE library, and the SCAD API contains some non-SCAD functionality already.

**Comment by kaosat-dev** [comment]
@z3dev I agree mostly :)
- I still believe that we should only have ONE API ,l also agreed on the CSG changes (still ongoing) 
- this proposal is just one of the many things I noticed while cleaning up the code (needed before the overall reorganization of CSG into core & API since API would be a **mix between the CSG API and this one )**
- there never was a 'compatibility layer' to Openscad, just an API trying to mimick it : and to be honest I think It is time for us to 'grow up' and not just copy it blindly, we can have a functional API that is familiar to but not 100% like Openscad
- this specific proposal im not 100% sure of, but it is one of the many ways to have a more thought out API that is specific to our language (js ;)

**Comment by z3dev** [comment]
V2 modeling uses rest parameters, followed by a function call to flatten arrays. So, this functionality has been implemented.

of course, this will not be implemented in the SCAD compatibility layer.
