### ISSUE TITLE
Move this to JSCAD Community.

### ISSUE THREAD

**Issue by z3dev** [jscad/scad-api#39]
If this project is out of scope for inclusion in OpenJSCAD.org, then how about moving this to the JSCAD Community? Or if this will not be used in the future then adding a comment as such?

**Comment by kaosat-dev** [comment]
This will be obsoleted in the future I would guess given our merging of the old scad-api with all core features ?
'there can be only one' ? Also this is already an obsolete repo, since scad-api was merged into csg.js quite a long time ago :)
