### ISSUE TITLE
BUG: hull() fails with TypeError

### ISSUE THREAD

**Issue by z3dev** [jscad/scad-api#4]
_From @z3dev on January 4, 2016 3:42_

function main() {
// BUG: If resolution is changed to 18 then there's an error
// "TypeError: this.points[p1] is undefined"
    var r = 18;
    var a = CAG.circle({center: [-5,0], radius: 3, resolution: r});
    var b = CAG.circle({center: [+5,0], radius: 3, resolution: r});
    b = hull(a,b);
    return b;
}

_Copied from original issue: Spiritdude/OpenJSCAD.org#114_

**Comment by kaosat-dev** [comment]
Interestingly this version works: (without using the CAG namespace)
function main() {
var r = 18;
var a = circle({ r: 3, $fn: r});
var b = circle({r: 3, $fn: r});
b = hull(a,b);
return b;
}

**Comment by z3dev** [comment]
Not relevant anymore.
